"use client";

import type { Article } from "@/components/article/columns";
import { Collaborator } from "@/components/collaborator/columns";

export const articleData: Article[] = [
  {
    id: "1",
    serieNbr: "CF123456",
    title: "Chemise en coton homme",
    category: "Matière première",
    unitCost: 25.99,
    salePrice: 49.99,
    stock: 50,
    unit: "pcs",
  },
  {
    id: "2",
    serieNbr: "CF654321",
    title: "Robe d'été florale",
    category: "Produit",
    unitCost: 30.5,
    salePrice: 59.99,
    stock: 30,
    unit: "pcs",
  },
  {
    id: "3",
    serieNbr: "CF987654",
    title: "Jean slim homme",
    category: "Produit",
    unitCost: 40.0,
    salePrice: 79.99,
    stock: 45,
    unit: "pcs",
  },
  {
    id: "4",
    serieNbr: "CF456789",
    title: "Veste en cuir femme",
    category: "consommable",
    unitCost: 120.0,
    salePrice: 199.99,
    stock: 15,
    unit: "pcs",
  },
  {
    id: "5",
    serieNbr: "CF741852",
    title: "Chaussures en cuir",
    category: "Produit",
    unitCost: 55.99,
    salePrice: 99.99,
    stock: 35,
    unit: "pcs",
  },
  {
    id: "6",
    serieNbr: "CF852963",
    title: "Sac à main en cuir",
    category: "Matière première",
    unitCost: 75.0,
    salePrice: 149.99,
    stock: 20,
    unit: "pcs",
  },
  {
    id: "7",
    serieNbr: "CF369258",
    title: "Bonnet en laine",
    category: "consommable",
    unitCost: 10.0,
    salePrice: 24.99,
    stock: 60,
    unit: "pcs",
  },
  {
    id: "8",
    serieNbr: "CF147258",
    title: "Écharpe en cachemire",
    category: "Matière première",
    unitCost: 35.0,
    salePrice: 79.99,
    stock: 25,
    unit: "pcs",
  },
  {
    id: "9",
    serieNbr: "CF963741",
    title: "Gants en cuir",
    category: "Matière première",
    unitCost: 20.0,
    salePrice: 49.99,
    stock: 40,
    unit: "pcs",
  },
  {
    id: "10",
    serieNbr: "CF258369",
    title: "Montre en acier inoxydable",
    category: "Matière première",
    unitCost: 90.0,
    salePrice: 199.99,
    stock: 10,
    unit: "pcs",
  },
];


export const collaboratorData:Collaborator[]=[
  {
    id: "1",
    nomDeFamille: "Durand",
    prenom: "Alice",
    reference: "COL001",
    idFiscale: "FR1029384756",
    type: "Entreprise",
    activite: "Informatique",
    dateAjout: new Date("2025-04-01"),
  },
  {
    id: "2",
    nomDeFamille: "Bernard",
    prenom: "Lucas",
    reference: "COL002",
    idFiscale: "FR5647382910",
    type: "Particulier",
    activite: "Design",
    dateAjout: new Date("2025-04-02"),
  },
  {
    id: "3",
    nomDeFamille: "Lemoine",
    prenom: "Camille",
    reference: "COL003",
    idFiscale: "FR1928374650",
    type: "Entreprise",
    activite: "Marketing",
    dateAjout: new Date("2025-04-03"),
  },
  {
    id: "4",
    nomDeFamille: "Martin",
    prenom: "Julien",
    reference: "COL004",
    idFiscale: "FR0192837465",
    type: "Particulier",
    activite: "Photographie",
    dateAjout: new Date("2025-04-04"),
  },
  {
    id: "5",
    nomDeFamille: "Nguyen",
    prenom: "Sarah",
    reference: "COL005",
    idFiscale: "FR2039485761",
    type: "Entreprise",
    activite: "Consulting",
    dateAjout: new Date("2025-04-05"),
  },
  {
    id: "6",
    nomDeFamille: "Fabre",
    prenom: "Antoine",
    reference: "COL006",
    idFiscale: "FR1203948576",
    type: "Particulier",
    activite: "Développement Web",
    dateAjout: new Date("2025-04-06"),
  },
  {
    id: "7",
    nomDeFamille: "Olivier",
    prenom: "Chloé",
    reference: "COL007",
    idFiscale: "FR9384756102",
    type: "Entreprise",
    activite: "Traduction",
    dateAjout: new Date("2025-04-07"),
  },
  {
    id: "8",
    nomDeFamille: "Roux",
    prenom: "Matthieu",
    reference: "COL008",
    idFiscale: "FR4756102938",
    type: "Particulier",
    activite: "Écriture",
    dateAjout: new Date("2025-04-08"),
  },
  {
    id: "9",
    nomDeFamille: "Marchand",
    prenom: "Isabelle",
    reference: "COL009",
    idFiscale: "FR9485761023",
    type: "Entreprise",
    activite: "Formation",
    dateAjout: new Date("2025-04-09"),
  },
  {
    id: "10",
    nomDeFamille: "Lopez",
    prenom: "Jules",
    reference: "COL010",
    idFiscale: "FR2938475610",
    type: "Particulier",
    activite: "Musique",
    dateAjout: new Date("2025-04-10"),
  },
  {
    id: "11",
    nomDeFamille: "Garnier",
    prenom: "Emma",
    reference: "COL011",
    idFiscale: "FR2039487561",
    type: "Entreprise",
    activite: "Communication",
    dateAjout: new Date("2025-04-11"),
  },
  {
    id: "12",
    nomDeFamille: "Masson",
    prenom: "Théo",
    reference: "COL012",
    idFiscale: "FR8374651920",
    type: "Particulier",
    activite: "Architecture",
    dateAjout: new Date("2025-04-12"),
  },
  {
    id: "13",
    nomDeFamille: "Chevalier",
    prenom: "Lucie",
    reference: "COL013",
    idFiscale: "FR5647382910",
    type: "Entreprise",
    activite: "Événementiel",
    dateAjout: new Date("2025-04-13"),
  },
  {
    id: "14",
    nomDeFamille: "Rodriguez",
    prenom: "Paul",
    reference: "COL014",
    idFiscale: "FR0192837465",
    type: "Particulier",
    activite: "Peinture",
    dateAjout: new Date("2025-04-14"),
  },
  {
    id: "15",
    nomDeFamille: "Petit",
    prenom: "Nina",
    reference: "COL015",
    idFiscale: "FR2039485761",
    type: "Entreprise",
    activite: "Vidéo",
    dateAjout: new Date("2025-04-15"),
  },
  
]